version: '3.1'

services:
  currency-converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:80
    image: 'heisln-currency-converter'
    container_name: 'heisln-currency-converter'
    networks:
      - heisln-net

networks:
  heisln-net:
    external: true
